# Generated by Django 6.0 on 2026-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
