# Generated by Django 6.0 on 2026-03-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=250)),
                ('thumbnail_url', models.FileField(upload_to='thumbnails/')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy')], default='Action', max_length=20)),
            ],
        ),
    ]
