# Generated by Django 6.0 on 2026-02-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='descripition',
            new_name='description',
        ),
    ]
