# Generated by Django 6.0 on 2026-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Crime', 'Crime'), ('Musical', 'Musical'), ('War', 'War'), ('Western', 'Western'), ('Other', 'Other')], max_length=50),
        ),
    ]
